#!/bin/bash

case "$BLOCK_BUTTON" in
1) notify-send "Left click detected on test block" ;;
2) notify-send "Middle click detected on test block" ;;
3) notify-send "Right click detected on test block" ;;
*) ;;
esac

# Always display something to make the block visible
echo "TEST2"
